BIN           := myapp
ALL_PLATFORMS := linux/amd64 darwin/amd64 windows/amd64
OS            := $(if $(GOOS),$(GOOS),$(shell go env GOOS))
ARCH          := $(if $(GOARCH),$(GOARCH),$(shell go env GOARCH))
OUTBIN        := build/$(BIN)-$(OS)-$(ARCH)$(EXT)

all: build

build-windows-%: EXT = .exe

build-%:
	@$(MAKE) build                                     \
		--no-print-directory                           \
		GOOS=$(firstword $(subst -, , $*))             \
		GOARCH=$(lastword $(subst -, , $*)) EXT=$(EXT)

all-build: $(addprefix build-,$(subst /,-,$(ALL_PLATFORMS)))

build:
	@echo "Building: OS=$(OS), ARCH=$(ARCH), OUTBIN=$(OUTBIN)"
